# Generated by Django 4.2.7 on 2024-10-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
    ]
