# Generated by Django 4.2.7 on 2024-10-18 20:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='club_emblems/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
