# Generated by Django 4.2.7 on 2024-10-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_emblem_alter_club_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.CharField(default='Unknown League', max_length=100),
        ),
    ]
