# Generated by Django 4.2.7 on 2024-10-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_options_alter_transferhistory_options_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstatistics',
            options={'verbose_name': 'Player Statistics', 'verbose_name_plural': 'Player Statistics'},
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='players.player'),
        ),
    ]
