# Generated by Django 4.2.7 on 2024-10-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0002_alter_player_options_alter_transferhistory_options_and_more'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_clubs',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='players.player'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
