# Generated by Django 5.1.4 on 2024-12-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'LiveBroadcast',
                'verbose_name_plural': 'LiveBroadcasts',
            },
        ),
    ]
